"""
schema.py
---------
Kontrak input untuk dashboard-v2 setelah migrasi ke artifact
multidomain/reguler.

Form single claim dibagi menjadi:
- core input: field yang paling sering diisi manual
- advanced input: field kategorikal/numerik lanjutan

Beberapa fitur turunan tetap dihitung otomatis di scoring layer.
"""

CORE_INPUT_FEATURES = [
    "usia",
    "tarif_disetujui",
    "lama_rawat_hari",
    "severity_level_num",
    "jumlah_diagnosis_sekunder",
    "fktp_hist_count_before",
    "nonkap_hist_count_before",
    "flag_kelas_upgrade",
    "flag_status_nonaktif",
    "flag_meninggal",
    "flag_rawat_inap",
    "flag_special_cmg",
    "total_special_cmg",
]

ADVANCED_INPUT_FEATURES = [
    "jenis_kelamin",
    "hubungan_keluarga",
    "kelas_rawat_hak",
    "kelas_rawat_klaim",
    "segmen_kepesertaan",
    "status_kepesertaan",
    "kepemilikan_fktp",
    "jenis_fktp",
    "tingkat_layanan",
    "poli_tujuan",
    "segmen_peserta_klaim",
    "status_pulang",
    "kepemilikan_faskes",
    "jenis_faskes",
    "tipe_faskes",
    "jenis_pelayanan",
    "grup_diagnosis_utama",
    "kode_diagnosis_utama",
    "grup_tindakan_utama",
    "kode_tindakan_utama",
    "jenis_inacbg",
    "kategori_tindakan",
    "regional_tarif_num",
    "flag_rujukan_missing",
    "tarif_inacbg_dasar",
    "tarif_grouping",
    "jumlah_special_cmg_aktif",
    "jumlah_grup_diagnosis_sekunder",
    "nonkap_hist_total_before",
    "nonkap_hist_mean_before",
]

USER_INPUT_FEATURES = CORE_INPUT_FEATURES + ADVANCED_INPUT_FEATURES
FEATURES = USER_INPUT_FEATURES
ALL_MODEL_FEATURES = USER_INPUT_FEATURES

NUMERIC_INPUT_FEATURES = {
    "usia",
    "tarif_disetujui",
    "lama_rawat_hari",
    "severity_level_num",
    "jumlah_diagnosis_sekunder",
    "fktp_hist_count_before",
    "nonkap_hist_count_before",
    "flag_kelas_upgrade",
    "flag_status_nonaktif",
    "flag_meninggal",
    "flag_rawat_inap",
    "flag_special_cmg",
    "total_special_cmg",
    "jenis_kelamin",
    "hubungan_keluarga",
    "kelas_rawat_hak",
    "kelas_rawat_klaim",
    "segmen_kepesertaan",
    "status_kepesertaan",
    "kepemilikan_fktp",
    "jenis_fktp",
    "tingkat_layanan",
    "poli_tujuan",
    "segmen_peserta_klaim",
    "status_pulang",
    "kepemilikan_faskes",
    "jenis_faskes",
    "tipe_faskes",
    "jenis_pelayanan",
    "jenis_inacbg",
    "kategori_tindakan",
    "regional_tarif_num",
    "flag_rujukan_missing",
    "tarif_inacbg_dasar",
    "tarif_grouping",
    "jumlah_special_cmg_aktif",
    "jumlah_grup_diagnosis_sekunder",
    "nonkap_hist_total_before",
    "nonkap_hist_mean_before",
}

DEFAULT_INPUT_VALUES = {
    "usia": 30,
    "tarif_disetujui": 0.0,
    "lama_rawat_hari": 1.0,
    "severity_level_num": 1.0,
    "jumlah_diagnosis_sekunder": 0.0,
    "fktp_hist_count_before": 0.0,
    "nonkap_hist_count_before": 0.0,
    "flag_kelas_upgrade": 0,
    "flag_status_nonaktif": 0,
    "flag_meninggal": 0,
    "flag_rawat_inap": 1,
    "flag_special_cmg": 0,
    "total_special_cmg": 0.0,
    "jenis_kelamin": 0.0,
    "hubungan_keluarga": 0.0,
    "kelas_rawat_hak": 0.0,
    "kelas_rawat_klaim": 0.0,
    "segmen_kepesertaan": 0.0,
    "status_kepesertaan": 0.0,
    "kepemilikan_fktp": 0.0,
    "jenis_fktp": 0.0,
    "tingkat_layanan": 0.0,
    "poli_tujuan": 0.0,
    "segmen_peserta_klaim": 0.0,
    "status_pulang": 0.0,
    "kepemilikan_faskes": 0.0,
    "jenis_faskes": 0.0,
    "tipe_faskes": 0.0,
    "jenis_pelayanan": 0.0,
    "grup_diagnosis_utama": "",
    "kode_diagnosis_utama": "",
    "grup_tindakan_utama": "",
    "kode_tindakan_utama": "",
    "jenis_inacbg": 0.0,
    "kategori_tindakan": 0.0,
    "regional_tarif_num": 0.0,
    "flag_rujukan_missing": 0,
    "tarif_inacbg_dasar": 0.0,
    "tarif_grouping": 0.0,
    "jumlah_special_cmg_aktif": 0.0,
    "jumlah_grup_diagnosis_sekunder": 0.0,
    "nonkap_hist_total_before": 0.0,
    "nonkap_hist_mean_before": 0.0,
}

FEATURE_LABELS = {
    "usia": "Usia",
    "tarif_disetujui": "Tarif Disetujui",
    "lama_rawat_hari": "Lama Rawat (Hari)",
    "severity_level_num": "Severity Level",
    "jumlah_diagnosis_sekunder": "Jumlah Diagnosis Sekunder",
    "fktp_hist_count_before": "Riwayat Kunjungan FKTP",
    "nonkap_hist_count_before": "Riwayat Klaim Non-Kapitasi",
    "flag_kelas_upgrade": "Upgrade Kelas",
    "flag_status_nonaktif": "Status Kepesertaan Nonaktif",
    "flag_meninggal": "Status Pulang Meninggal",
    "flag_rawat_inap": "Rawat Inap",
    "flag_special_cmg": "Ada Special CMG",
    "total_special_cmg": "Total Special CMG",
    "jenis_kelamin": "Jenis Kelamin",
    "hubungan_keluarga": "Hubungan Keluarga",
    "kelas_rawat_hak": "Kelas Rawat Hak",
    "kelas_rawat_klaim": "Kelas Rawat Klaim",
    "segmen_kepesertaan": "Segmen Kepesertaan",
    "status_kepesertaan": "Status Kepesertaan",
    "kepemilikan_fktp": "Kepemilikan FKTP",
    "jenis_fktp": "Jenis FKTP",
    "tingkat_layanan": "Tingkat Layanan",
    "poli_tujuan": "Poli Tujuan",
    "segmen_peserta_klaim": "Segmen Peserta Klaim",
    "status_pulang": "Status Pulang",
    "kepemilikan_faskes": "Kepemilikan Faskes",
    "jenis_faskes": "Jenis Faskes",
    "tipe_faskes": "Tipe Faskes",
    "jenis_pelayanan": "Jenis Pelayanan",
    "grup_diagnosis_utama": "Grup Diagnosis Utama",
    "kode_diagnosis_utama": "Kode Diagnosis Utama",
    "grup_tindakan_utama": "Grup Tindakan Utama",
    "kode_tindakan_utama": "Kode Tindakan Utama",
    "jenis_inacbg": "Jenis INACBG",
    "kategori_tindakan": "Kategori Tindakan",
    "regional_tarif_num": "Regional Tarif",
    "flag_rujukan_missing": "Rujukan FKTP Missing",
    "tarif_inacbg_dasar": "Tarif INACBG Dasar",
    "tarif_grouping": "Tarif Grouping",
    "jumlah_special_cmg_aktif": "Jumlah Special CMG Aktif",
    "jumlah_grup_diagnosis_sekunder": "Jumlah Grup Diagnosis Sekunder",
    "nonkap_hist_total_before": "Total Riwayat Non-Kapitasi",
    "nonkap_hist_mean_before": "Rata-rata Riwayat Non-Kapitasi",
    "risk_score": "Skor Risiko",
    "risk_percent": "Persentase Risiko",
    "priority": "Prioritas Verifikasi",
    "threshold_used": "Threshold Model",
    "iforest_score": "Isolation Forest Score",
}
